### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by nntrn** [nntrn/save#52]
## Transforms

* [An Introduction to CSS 3-D Transforms][1]
* [Intro to CSS 3D transforms][2] by David Desandro
* [Text styling](https://developer.mozilla.org/en-US/docs/Learn_web_development/Core/Text_styling/Fundamentals)

## Font Family

```css
@font-face {
  font-family: "Ampersand";
  src: local("Times New Roman");
  unicode-range: U+26;
}

div {
  font-size: 4em;
  font-family: Ampersand, Helvetica, sans-serif;
}
```

[1]: https://24ways.org/2010/intro-to-css-3d-transforms/

[2]: https://3dtransforms.desandro.com/
