### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by nntrn** [nntrn/save#8]
## Only cancel in-progress jobs or runs for the current workflow

```yaml
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
```
